Refactor data generation to be cleaner and more principled.
cargo-semver-checks outgrew its previous data generation system. Over the previous 2+ years, this code was slowly turning into spaghetti as we discovered we needed to add ever more functionality and work around ever more issues. It was borderline unmaintainable, and impossible to extend in a meaningful fashion.

As part of https://github.com/rust-lang/rust-project-goals/issues/104, we aim to start supporting manifest linting. That would require generating more data -- not just rustdoc JSON but also project metadatasuch as package features and targets. Plumbing that data though the existing data generation spaghetti code was proving infeasible.

This PR tackles the lion's share of the spaghetti problem. It introduces a new submodule, `data_generation`, that handles data generation tasks and has its own internal invariants and data structures which are not tied into CLI considerations like "should we use color when printing to the terminal". That will make it easier to extend with project metadata in subsequent PRs.

There is still some clean-up work remaining -- this PR is just the start of that work. But here we untangle the biggest mess in the tool, which will let us move more quickly elsewhere.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -406,14 +406,15 @@ jobs:
 
           # Show what's in the cache.
           ls subject-new/target/semver-checks/cache/
+          EXPECTED_CACHED_RUSTDOC='subject-new/target/semver-checks/cache/libp2p_core-0_37_0-ccce455725cbab73.json'
 
           # Ensure the previous cached rustdoc file still exists.
-          [ -f "subject-new/target/semver-checks/cache/registry-libp2p_core-0_37_0.json" ] || { \
+          [ -f "$EXPECTED_CACHED_RUSTDOC" ] || { \
             echo "could not find libp2p-core cache file"; \
             exit 1;
           }
 
-          export OLD_RUSTDOC_VERSION="$(jq .format_version subject-new/target/semver-checks/cache/registry-libp2p_core-0_37_0.json)"
+          export OLD_RUSTDOC_VERSION="$(jq .format_version "$EXPECTED_CACHED_RUSTDOC")"
 
           # Run cargo-semver-checks with the older cached file.
           # In a prior step, we installed a newer Rust, so we'll set that as the default
@@ -421,13 +422,16 @@ jobs:
           rustup override set "$NEWER_RUST"
           bins/cargo-semver-checks semver-checks check-release --manifest-path="subject-new/core/Cargo.toml" --verbose
 
-          export NEW_RUSTDOC_VERSION="$(jq .format_version subject-new/target/semver-checks/cache/registry-libp2p_core-0_37_0.json)"
+          # Show what's in the cache now.
+          ls subject-new/target/semver-checks/cache/
+
+          export NEW_RUSTDOC_VERSION="$(jq .format_version "$EXPECTED_CACHED_RUSTDOC")"
 
           # Ensure the cached rustdoc versions were indeed different before and after.
           [ "$OLD_RUSTDOC_VERSION" != "$NEW_RUSTDOC_VERSION" ] || exit 1
 
   cross-feature-caching:
-    # Ensure that cached rustdoc JSON files created with mismatched feature config is not used.
+    # Ensure that cached rustdoc JSON files created with mismatched feature config are not used.
     name: 'Caching with feature config changed'
     runs-on: ubuntu-latest
     needs:
@@ -479,8 +483,19 @@ jobs:
       # Run even if there was a cache hit, to make sure the check passes.
       - name: Run semver-checks
         run: |
-          cd semver
-          ../bins/cargo-semver-checks semver-checks check-release --manifest-path="../subject/serde/Cargo.toml" --verbose
+          bins/cargo-semver-checks semver-checks check-release --manifest-path="subject/serde/Cargo.toml" --verbose
+
+          # Show what's in the cache.
+          ls subject/target/semver-checks/cache/
+
+      # Save the older rustdoc on cache miss. This must run *before* the cross-feature check,
+      # since we don't want to save that rustdoc -- we're making sure it gets generated and used!
+      - name: Save rustdoc
+        uses: actions/cache/save@v4
+        if: steps.cache.outputs.cache-hit != 'true'
+        with:
+          key: cross-feature-caching-${{ runner.os }}-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('semver/**/Cargo.lock') }}-${{ github.job }}-rustdoc
+          path: subject/target/semver-checks/cache
 
       # Run cargo-semver-checks, enabling feature `unstable` this time.
       # We expect this to fail.
@@ -508,20 +523,30 @@ jobs:
 
       - name: Verify cached rustdoc's hash
         run: |
-          if [ -f subject/target/semver-checks/cache/registry-serde-1_0_162-f0dcb72a80405fd6.json ]; then exit 0; else exit 1; fi
+          # Show what's in the cache.
+          ls subject/target/semver-checks/cache/
+
+          # The previous cached rustdoc should continue to exist.
+          if [ -f subject/target/semver-checks/cache/serde-1_0_162-5900ebf8bb9b9f8b.json ]; then
+            exit 0
+          else
+            echo "Older rustdoc JSON not found in cache!"
+            exit 1
+          fi
+
+          # There should also be a new cached rustdoc file for the new feature settings.
+          if [ -f subject/target/semver-checks/cache/serde-1_0_162-6999ae87ca463ab3.json ]; then
+            exit 0
+          else
+            echo "New rustdoc JSON for new feature combo not found in cache!"
+            exit 1
+          fi
 
       - name: Cleanup
         run: |
           cd semver
           rm output
           rm -f unexpectedly_did_not_fail
-
-      - name: Save rustdoc
-        uses: actions/cache/save@v4
-        if: steps.cache.outputs.cache-hit != 'true'
-        with:
-          key: cross-feature-caching-${{ runner.os }}-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('semver/**/Cargo.lock') }}-${{ github.job }}-rustdoc
-          path: subject/target/semver-checks/cache
 
   run-on-rust-libp2p:
     # Run cargo-semver-checks on a crate with no semver violations,
