Load lib target name from `cargo metadata`. (#433)
* Load lib target name from `cargo metadata`.

* Clean up test cases.

* Reproduce the `perf-event-open-sys2` crash in CI.

* Restore old behavior around bin targets.

* Support proc macro crates too.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,6 +38,7 @@ jobs:
       - run-on-ref-slice-fork-windows
       - run-on-tokio-explicit
       - run-on-tokio-implicit
+      - run-on-perf-event-open-sys2
     if: ${{ success() || failure() }}  # Run this job even if a dependency has failed.
     steps:
       - name: Job outcomes
@@ -58,6 +59,7 @@ jobs:
           echo "run-on-ref-slice-fork-windows: ${{ needs.run-on-ref-slice-fork-windows.result }}"
           echo "run-on-tokio-explicit: ${{ needs.run-on-tokio-explicit.result }}"
           echo "run-on-tokio-implicit: ${{ needs.run-on-tokio-implicit.result }}"
+          echo "run-on-perf-event-open-sys2: ${{ needs.run-on-perf-event-open-sys2.result }}"
 
       # Fail this required job if any of its dependent jobs have failed.
       #
@@ -95,6 +97,8 @@ jobs:
       - if: ${{ needs.run-on-tokio-explicit.result != 'success' }}
         run: exit 1
       - if: ${{ needs.run-on-tokio-implicit.result != 'success' }}
+        run: exit 1
+      - if: ${{ needs.run-on-perf-event-open-sys2.result != 'success' }}
         run: exit 1
 
   lint:
@@ -1318,6 +1322,66 @@ jobs:
         with:
           key: ${{ runner.os }}-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('semver\**\Cargo.lock') }}-${{ github.job }}-rustdoc
           path: subject\target\semver-checks\cache
+
+  run-on-perf-event-open-sys2:
+    # cargo-semver-checks failed to find the generated rustdoc JSON
+    # because the crate used a lib name different from the crate name.
+    # https://github.com/obi1kenobi/cargo-semver-checks/issues/432
+    name: 'Semver: perf-event-open-sys2 v5.0.0'
+    runs-on: ubuntu-latest
+    needs:
+      - build-binary
+    steps:
+      - name: Checkout cargo-semver-checks
+        uses: actions/checkout@v3
+        with:
+          persist-credentials: false
+          path: 'semver'
+
+      - name: Checkout bevy
+        uses: actions/checkout@v3
+        with:
+          persist-credentials: false
+          repository: 'phantomical/perf-event'
+          ref: '47dc882dbfb44b86584540a6e4f2815caaf72c10'
+          path: 'subject'
+
+      - name: Install rust
+        id: toolchain
+        uses: dtolnay/rust-toolchain@stable
+
+      - name: Restore binary
+        id: cache-binary
+        uses: actions/cache/restore@v3
+        with:
+          path: bins/
+          key: bins-${{ runner.os }}-${{ github.run_id }}-${{ github.run_attempt }}
+          fail-on-cache-miss: true
+
+      - name: Restore rustdoc
+        id: cache
+        uses: actions/cache/restore@v3
+        with:
+          key: ${{ runner.os }}-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('semver/**/Cargo.lock') }}-${{ github.job }}-rustdoc
+          path: subject/target/semver-checks/cache
+
+      - name: Restore cargo index and rustdoc target dir
+        uses: Swatinem/rust-cache@v2
+        with:
+          workspaces: |
+            subject/target/semver-checks/local-perf-event-open-sys2-5_0_0
+
+      - name: Run semver-checks
+        run: |
+          cd semver
+          ../bins/cargo-semver-checks semver-checks check-release --manifest-path="../subject/perf-event-open-sys/Cargo.toml" --baseline-version 5.0.0 --verbose
+
+      - name: Save rustdoc
+        uses: actions/cache/save@v3
+        if: steps.cache.outputs.cache-hit != 'true'
+        with:
+          key: ${{ runner.os }}-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('semver/**/Cargo.lock') }}-${{ github.job }}-rustdoc
+          path: subject/target/semver-checks/cache
 
   init-release:
     name: Run the release workflow
