Add ability to specify features in CLI (#426)
* Create interface

* Implement most of the logic

* Add ability to specify different features per version

* Adjust the info message

* Fix clippy issues

* Finish off implementation

* Adjust behaviour for --default-features

* Fix tests

* Add tests

* Use feature identifiers not only for caching

* Add another test

* Adjust caching test in CI

* Remove hash from path when using default feature config

* Add test to CI: feature config + cache interaction

* Fix

* Clean up CI changes

* Add the job as dependency

* Fix typo

* Remove rm

* Add the rm back?

* Add set

* Make sure heuristic uses default features

* Review adjustments

* Add another comment

* Rework the hashing

* Add test checking hash value

* Add <> to link for rustdoc

* Review adjustments

* Add periods and enable default features with --all-features

* Fix the hashing

* Fix hash value in test

* Adjust CLI messages and comments

---------

Co-authored-by: Predrag Gruevski <2348618+obi1kenobi@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,6 +25,7 @@ jobs:
       - lint
       - rust-tests
       - cross-version-caching
+      - cross-feature-caching
       - run-on-rust-libp2p
       - run-on-libp2p-dcutr-relay
       - run-on-libp2p-gossipsub-request-response
@@ -47,6 +48,7 @@ jobs:
           echo "lint: ${{ needs.lint.result }}"
           echo "rust-tests: ${{ needs.rust-tests.result }}"
           echo "cross-version-caching: ${{ needs.cross-version-caching.result }}"
+          echo "cross-feature-caching: ${{ needs.cross-feature-caching.result }}"
           echo "run-on-rust-libp2p: ${{ needs.run-on-rust-libp2p.result }}"
           echo "run-on-libp2p-dcutr-relay: ${{ needs.run-on-libp2p-dcutr-relay.result }}"
           echo "run-on-libp2p-gossipsub-request-response: ${{ needs.run-on-libp2p-gossipsub-request-response.result }}"
@@ -73,6 +75,8 @@ jobs:
       - if: ${{ needs.rust-tests.result != 'success' }}
         run: exit 1
       - if: ${{ needs.cross-version-caching.result != 'success' }}
+        run: exit 1
+      - if: ${{ needs.cross-feature-caching.result != 'success' }}
         run: exit 1
       - if: ${{ needs.run-on-rust-libp2p.result != 'success' }}
         run: exit 1
@@ -356,6 +360,100 @@ jobs:
           # Ensure the cached rustdoc versions were indeed different before and after.
           set -x
           [ "$OLD_RUSTDOC_VERSION" != "$NEW_RUSTDOC_VERSION" ] || exit 1
+
+  cross-feature-caching:
+    # Ensure that cached rustdoc JSON files created with mismatched feature config is not used.
+    name: 'Caching with feature config changed'
+    runs-on: ubuntu-latest
+    needs:
+      - build-binary
+    steps:
+      - name: Checkout cargo-semver-checks
+        uses: actions/checkout@v3
+        with:
+          persist-credentials: false
+          path: 'semver'
+
+      # This is a fork of serde, modified to make feature `unstable` break semver.
+      - name: Checkout fork of serde
+        uses: actions/checkout@v3
+        with:
+          persist-credentials: false
+          repository: 'staniewzki/serde'
+          ref: 'c479da812fd421260667c02049e6d11edd82c2dc'
+          path: 'subject'
+
+      - name: Restore binary
+        id: cache-binary
+        uses: actions/cache/restore@v3
+        with:
+          path: bins/
+          key: bins-${{ runner.os }}-${{ github.run_id }}-${{ github.run_attempt }}
+          fail-on-cache-miss: true
+
+      - name: Install rust
+        id: toolchain
+        uses: dtolnay/rust-toolchain@stable
+
+      - name: Restore rustdoc
+        id: cache
+        uses: actions/cache/restore@v3
+        with:
+          key: cross-feature-caching-${{ runner.os }}-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('semver/**/Cargo.lock') }}-${{ github.job }}-rustdoc
+          path: subject/target/semver-checks/cache
+
+      - name: Restore cargo index and rustdoc target dir
+        uses: Swatinem/rust-cache@v2
+        with:
+          workspaces: |
+            subject/target/semver-checks/local-serde-1_0_162
+
+      # Run even if there was a cache hit, to make sure the check passes.
+      - name: Run semver-checks
+        run: |
+          cd semver
+          ../bins/cargo-semver-checks semver-checks check-release --manifest-path="../subject/serde/Cargo.toml" --verbose
+
+      # Run cargo-semver-checks, enabling feature `unstable` this time.
+      # We expect this to fail.
+      # This run must not use the `serde` rustdoc without this feature as a baseline.
+      # If that happens, this check will unexpectedly pass -- and the test will fail.
+      - name: Check with rustdoc for mismatching feature config cached
+        continue-on-error: true
+        run: |
+          cd semver
+          set -euo pipefail
+          ../bins/cargo-semver-checks semver-checks check-release --manifest-path="../subject/serde/Cargo.toml" --verbose --features unstable | tee output
+          touch unexpectedly_did_not_fail
+
+      - name: Check whether it failed
+        run: |
+          cd semver
+          if [ -f unexpectedly_did_not_fail ]; then exit 1; else exit 0; fi
+
+      - name: Check output
+        run: |
+          cd semver
+          EXPECTED="$(echo -e "--- failure struct_missing: pub struct removed or renamed ---")"
+          RESULT="$(cat output | grep failure)"
+          diff <(echo "$RESULT") <(echo "$EXPECTED")
+
+      - name: Verify cached rustdoc's hash
+        run: |
+          if [ -f subject/target/semver-checks/cache/registry-serde-1_0_162-f0dcb72a80405fd6.json ]; then exit 0; else exit 1; fi
+
+      - name: Cleanup
+        run: |
+          cd semver
+          rm output
+          rm -f unexpectedly_did_not_fail
+
+      - name: Save rustdoc
+        uses: actions/cache/save@v3
+        if: steps.cache.outputs.cache-hit != 'true'
+        with:
+          key: cross-feature-caching-${{ runner.os }}-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('semver/**/Cargo.lock') }}-${{ github.job }}-rustdoc
+          path: subject/target/semver-checks/cache
 
   run-on-rust-libp2p:
     # Run cargo-semver-checks on a crate with no semver violations,
