Add manufactured semver break test from GitHub Action.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,6 +29,7 @@ jobs:
       - run-on-clap
       - run-on-sqllogictest
       - run-on-tokio
+      - run-on-ref-slice-fork
     steps:
       - run: exit 0
 
@@ -541,6 +542,73 @@ jobs:
           EXPECTED="$(echo -e "--- failure auto_trait_impl_removed: auto trait no longer implemented ---\n--- failure trait_missing: pub trait removed or renamed ---")"
           RESULT="$(cat output | grep failure)"
           diff <(echo "$RESULT") <(echo "$EXPECTED")
+
+  run-on-ref-slice-fork:
+    # Simulate testing an as-yet-unreleased crate version without an explicit baseline,
+    # i.e. with the expectation that the largest crates.io version is used as a baseline.
+    # This broke when a PR accidentally changed the default baseline behavior.
+    # https://github.com/obi1kenobi/cargo-semver-checks/issues/382
+    #
+    # To perform this test, we forked a stable crate and made a semver-major change in
+    # an unreleased patch version (v1.2.2). In this test, we make sure that:
+    # - v1.2.1 is chosen as the baseline, as the largest crates.io version,
+    # - cargo-semver-checks detects the semver break we've manufactured.
+    name: Run cargo-semver-checks on ref-slice fork
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout cargo-semver-checks
+        uses: actions/checkout@v3
+        with:
+          persist-credentials: true
+
+      - name: Checkout ref-slice fork semver break
+        uses: actions/checkout@v3
+        with:
+          persist-credentials: false
+          repository: 'mgr0dzicki/cargo-semver-action-ref-slice'
+          ref: 'major_change'
+          path: 'subject'
+
+      - name: Install rust
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+          profile: minimal
+          override: true
+
+      - uses: Swatinem/rust-cache@v2
+        with:
+          key: ref-slice-fork
+
+      - name: Run semver-checks
+        continue-on-error: true
+        run: |
+          cargo run semver-checks check-release --manifest-path="subject/Cargo.toml" > output
+          touch unexpectedly_did_not_fail
+
+      - name: Check whether it failed
+        run: |
+          if [ -f unexpectedly_did_not_fail ]; then exit 1; else exit 0; fi
+
+      - name: Baseline is correct
+        run: |
+          EXPECTED="$(echo -e "     Parsing ref_slice v1.2.2 (current)\n     Parsing ref_slice v1.2.1 (baseline)\n    Checking ref_slice v1.2.1 -> v1.2.2 (patch change)")"
+          RESULT="$(cat output | grep 'ref_slice v1.')"
+          diff <(echo "$RESULT") <(echo "$EXPECTED")
+
+      - name: Semver break found
+        run: |
+          EXPECTED="$(echo -e "--- failure function_missing: pub fn removed or renamed ---")"
+          RESULT="$(cat output | grep failure')"
+          diff <(echo "$RESULT") <(echo "$EXPECTED")
+          EXPECTED="$(echo -e "  function ref_slice::ref_slice, previously in file")"
+          RESULT="$(cat output | grep 'previously in file')"
+          diff <(echo "$RESULT") <(echo "$EXPECTED")
+
+      - name: Cleanup
+        run: |
+          rm output
+          rm -f unexpectedly_did_not_fail
 
   init-release:
     name: Run the release workflow
