Changed all baseline rustdoc generations to use placeholder manifest (#341)
* Changed all baseline rustdoc generations to use placeholder manifest

* Add comment

Co-authored-by: Predrag Gruevski <2348618+obi1kenobi@users.noreply.github.com>

* Change unwrap to expect

* Add comments

* Changed argument order, commented arguments

* Added msg to assert

* Changed comments to doc comments

* Undo the comment change

* Changed returned String to &str

* Added a job that tests --baseline-rev

* CI job bugfix attempt

* typo

* come on CI, work

* Added git fetch in job before using --baseline-rev

* Changed comments to doc comments

* Changed bare URLs to clickable links in rustdoc

* Hopefully now fetching in the correct directory

* Corrected commit hash

* Changed file name in CI job

---------

Co-authored-by: Predrag Gruevski <2348618+obi1kenobi@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -373,15 +373,42 @@ jobs:
         with:
           key: clap
 
-      - name: Run semver-checks
+      - name: Run semver-checks with --baseline-root
         continue-on-error: true
         run: |
           cargo run semver-checks check-release --manifest-path="subject-current/Cargo.toml" --baseline-root="subject-baseline/Cargo.toml" > output
-          echo "$?" > return_code
+          touch unexpectedly_did_not_fail
 
-      - name: Check return code
+      - name: Check whether it failed
         run: |
-          if [[ "$(cat return_code)" == "0" ]]; then exit 1; else exit 0; fi
+          if [ -f unexpectedly_did_not_fail ]; then exit 1; else exit 0; fi
+
+      - name: Check output
+        run: |
+          EXPECTED="$(echo -e "--- failure auto_trait_impl_removed: auto trait no longer implemented ---\n--- failure trait_missing: pub trait removed or renamed ---")"
+          RESULT="$(cat output | grep failure)"
+          diff <(echo "$RESULT") <(echo "$EXPECTED")
+
+      - name: Cleanup
+        run: |
+          rm output
+          rm -f unexpectedly_did_not_fail
+
+      - name: Fetch v3.1.18 in subject-current
+        run: |
+          cd subject-current
+          git fetch origin 524e36cf1a67ee6a447d3615a70b065d2b4f5e60
+          cd ..
+
+      - name: Run semver-checks with --baseline-rev
+        continue-on-error: true
+        run: |
+          cargo run semver-checks check-release --manifest-path="subject-current/Cargo.toml" --baseline-rev=524e36cf1a67ee6a447d3615a70b065d2b4f5e60 > output
+          touch unexpectedly_did_not_fail
+
+      - name: Check whether it failed
+        run: |
+          if [ -f unexpectedly_did_not_fail ]; then exit 1; else exit 0; fi
 
       - name: Check output
         run: |
