Support linting breaking changes in manifests & add `feature_missing` lint (#1007)
Add support for linting of package manifests, allowing us to scan for
breaking changes there as well.

For example, deleting a feature is a major breaking change. As of this
PR, we can detect and report that:
```
--- failure feature_missing: package feature removed or renamed ---

Description:
A feature has been removed from this package's Cargo.toml. This will break downstream crates which enable that feature.
        ref: https://doc.rust-lang.org/cargo/reference/semver.html#cargo-feature-remove
       impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.37.0/src/lints/feature_missing.ron

Failed in:
  feature going_missing in the package's Cargo.toml
  feature rand in the package's Cargo.toml

     Summary semver requires new major version: 1 major and 0 minor checks failed
```

Completes the first checkbox of the 2024H2 Rust Project Goal on
cargo-semver-checks:
https://github.com/rust-lang/rust-project-goals/issues/104

Unblocks the lints specified in #48.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -194,7 +194,7 @@ jobs:
         uses: actions/cache@v4
         with:
           path: semver/localdata/test_data/
-          key: test-rustdocs-${{ runner.os }}-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('semver/test_crates/**/*.rs') }}
+          key: test-rustdocs-and-meta-${{ runner.os }}-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('semver/test_crates/**/*.rs') }}
 
       - name: Regenerate test data
         if: steps.cache-test-rustdocs.outputs.cache-hit != 'true'
@@ -406,11 +406,17 @@ jobs:
 
           # Show what's in the cache.
           ls subject-new/target/semver-checks/cache/
-          EXPECTED_CACHED_RUSTDOC='subject-new/target/semver-checks/cache/libp2p_core-0_37_0-ccce455725cbab73.json'
+          EXPECTED_PREFIX='subject-new/target/semver-checks/cache/libp2p_core-0_37_0-ccce455725cbab73'
+          EXPECTED_CACHED_METADATA="${EXPECTED_PREFIX}.metadata.json"
+          EXPECTED_CACHED_RUSTDOC="${EXPECTED_PREFIX}.json"
 
-          # Ensure the previous cached rustdoc file still exists.
+          # Ensure the previous cached rustdoc and metadata files still exist.
+          [ -f "$EXPECTED_CACHED_METADATA" ] || { \
+            echo "could not find libp2p-core metadata cache file"; \
+            exit 1;
+          }
           [ -f "$EXPECTED_CACHED_RUSTDOC" ] || { \
-            echo "could not find libp2p-core cache file"; \
+            echo "could not find libp2p-core rustdoc cache file"; \
             exit 1;
           }
 
@@ -527,18 +533,28 @@ jobs:
           ls subject/target/semver-checks/cache/
 
           # The previous cached rustdoc should continue to exist.
-          if [ -f subject/target/semver-checks/cache/serde-1_0_162-5900ebf8bb9b9f8b.json ]; then
-            exit 0
-          else
+          PREVIOUS_PREFIX='subject/target/semver-checks/cache/serde-1_0_162-5900ebf8bb9b9f8b'
+          PREVIOUS_RUSTDOC="${PREVIOUS_PREFIX}.json"
+          PREVIOUS_METADATA="${PREVIOUS_PREFIX}.metadata.json"
+          if [ ! -f "$PREVIOUS_RUSTDOC" ]; then
             echo "Older rustdoc JSON not found in cache!"
+            exit 1
+          fi
+          if [ ! -f "$PREVIOUS_METADATA" ]; then
+            echo "Older metadata file not found in cache!"
             exit 1
           fi
 
           # There should also be a new cached rustdoc file for the new feature settings.
-          if [ -f subject/target/semver-checks/cache/serde-1_0_162-6999ae87ca463ab3.json ]; then
-            exit 0
-          else
+          NEW_PREFIX='subject/target/semver-checks/cache/serde-1_0_162-6999ae87ca463ab3'
+          NEW_RUSTDOC="${NEW_PREFIX}.json"
+          NEW_METADATA="${NEW_PREFIX}.metadata.json"
+          if [ ! -f "$NEW_RUSTDOC" ]; then
             echo "New rustdoc JSON for new feature combo not found in cache!"
+            exit 1
+          fi
+          if [ ! -f "$NEW_METADATA" ]; then
+            echo "New metadata file for new feature combo not found in cache!"
             exit 1
           fi
 
